#pragma once

#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 960

#define SHOOT_COOLDOWN 0.1f
#define SHOOT_TIMER 0.0
#define BULLET_VELOCITY 2000.0f

#define PLAYER_SCALE 2
#define PLAYER_SPEED 700.0f
